### ISSUE TITLE
Full-waveform support: point types 4, 5, 9, 10

### ISSUE THREAD

**Issue by ericrehm** [Jean-Romain/rlas#31]
Our LiDAR is full-waveform.  We would like to read/write, i.e., point type 4 (and 9, 10).  

To start with, I could live with a read-only (read.las) solution that ignores the full-waveform VLRs / EVLRs and associated waveform data in WDP files, i.e., just read the points that are there in the .LAS/.LAZ file.   (Not sure if I can just use las2las for that....)

**Comment by Jean-Romain** [comment]
Point format 4 9 and 10 are not supported because I've never encounter such file. I hard coded an exit for these formats but in theory these formats should be supported simply by removing the conditional statement. By "supported" I mean just the points not the waveform.

To do so I need a file (tiny) in format 4, 9 or 10. Could you share that? With a FWF file example I could also enable support of the waveform in read mode.

**Comment by ericrehm** [comment]
I have sent you a very small Point format 4 LAS file (pulse, 3 returns) and the associated WDP file via email.  (I'm at ULaval too.)  It's the output of a new example that's part of LAStools, specifically, LAStools/LASlib/example/lasexample_write_full_waveform.cpp.   More here:  https://groups.google.com/forum/#!topic/lastools/OZMpTBe7roQ .

**Comment by Jean-Romain** [comment]
I pushed add8607 in the `devel` branch with a support of full waveform format 4,5,9,10 (point cloud only). The support of the waveform will take me much more time. Also there is no support for writing format 4,5,9,10. If you are also a user of the lidR package, you must update also this package because this new version of `rlas` brings a support of LAS 1.4 with few minor incompatibilities fixed in  lidR 2.0.1.

**Comment by Jean-Romain** [comment]
I pushed a first tentative of FWF support in read mode. It works and is compatible with lidR. There is still some work to achieve but lot of things are still unclear to me in the LAS specification. But anyway it is a great achievement for a single day!

```r
las = rlas::read.las("/home/jr/Téléchargements/out.las", select = "xyzW")
las
#>           X       Y      Z    FullWaveForm
#> 1: 235374.7 5800928 276.50 0,0,0,0,0,0,...
#> 2: 235376.0 5800928 272.84 0,0,0,0,0,0,...
#> 3: 235377.4 5800928 268.72 0,0,0,0,0,0,...

plot(las$FullWaveForm[[1]], type = "l")
```

![rplot](https://user-images.githubusercontent.com/3872279/52082444-be3de800-256a-11e9-8c80-f68c74c99876.png)

**Comment by Jean-Romain** [comment]
Great improvements today. I read the FullWaveform + the WaveDataPacket and I made a function for FWF interpretation as the content is not trivial

```r
u = read.las("~/Téléchargements/out.las", select = "W")
h = read.lasheader("~/Téléchargements/out.las")

u

fwf = rlas::fwf_interpreter(h,u)[[1]]
xoffset = min(fwf$X)
yoffset = min(fwf$Y)

color.gradient <- function(x, colors=c("#ffebeb","red"), colsteps=100) 
{
  return(colorRampPalette(colors) (colsteps) [ findInterval(x, seq(min(x),max(x), length.out=colsteps)) ] )
}

col = color.gradient(fwf$Amplitude)

rgl::plot3d(fwf$X-xoffset, fwf$Y-yoffset, fwf$Z, xlim = c(-10,10), ylim = c(-10,10), zlim = c(265,280), col = col)
```

![capture du 2019-02-01 12-15-46](https://user-images.githubusercontent.com/3872279/52138427-20eebc80-261b-11e9-83f4-0e8668fccc57.png)

**Comment by Jean-Romain** [comment]
@ericrehm could you share a true FWF data? I'm not able to go further with a single synthetic pulse.

**Comment by Jean-Romain** [comment]
![animated](https://user-images.githubusercontent.com/3872279/52150799-0f1f1080-263f-11e9-99dc-5d4715aa214e.gif)

**Comment by ericrehm** [comment]
RE: animation


Génial!  /eri











/eric rehm


Professionnel de recherche / Research Associate

CERC sur la télédétection de la nouvelle frontière arctique du Canada

Unité Mixte Internationale Takuvik

http://www.takuvik.ulaval.ca/

418-656-2131 ext. 7677

418-254-7234 (mobile)

**Comment by Jean-Romain** [comment]
2 years later, I started to work back on it. I updated everything and fixed some stuff. I will try to provide a support of FWF soon
